### ISSUE TITLE
The `from` parameter is invalid

### ISSUE THREAD

**Issue by AI-General** [Vonage/vonage-curl-code-snippets#131]
Hi, I tried to send whatsapp message using this script:
`https://github.com/Vonage/vonage-curl-code-snippets/blob/692ef9cf6aecb6ef6fe8bd07ffc0f0ab7aa1527f/messages/whatsapp/send-text.sh`

But I met following error:
`{"title":"Invalid sender","detail":"The `from` parameter is invalid.","instance":"b39ef3a0-bf2f-4850-b2f1-6dd407b73c8c","type":"https://developer.nexmo.com/api-errors/messages#1120"}`

Please help me!!!

I see no issue on my end.

**Comment by pardel** [comment]
WhatsApp messages can only be sent by businesses that have been approved by WhatsApp. 

Please read more here: https://developer.vonage.com/en/messages/concepts/whatsapp?source=messages
