### ISSUE TITLE
Snippet for quick-relpy button doesn't work

### ISSUE THREAD

**Issue by eldar-mustafayev** [Vonage/vonage-curl-code-snippets#97]
I am trying to test WhatsApp quick reply button functionality through sandbox API. Although i got message_uuid as a response, the message didn't appear in my WhatsApp account.

Smartphone specifications: Xiaomi Mi 9SE, Android 10

**Comment by zhombie** [comment]
Same

**Comment by zhombie** [comment]
I have something interesting on my bound webhook, which is set as status events.

I got: 

`
{'message_uuid': '255acc6e-181d-40ac-b1f3-1e7b75e2a793', 'from': {'type': 'whatsapp', 'number': '14157386170'}, 'to': {'type': 'whatsapp', 'number': 'XXXXXXXX'}, 'error': {'reason': 'Invalid template or template parameters', 'code': 1022}, 'timestamp': '2021-05-17T15:36:49.011Z', 'status': 'rejected'}
`

**Comment by superchilled** [comment]
Hi @eldar-mustafayev are you using Messages v0.1 or Messages v1 endpoint? I just updated the code snippet to be Messages v1 version: https://developer.vonage.com/messages/code-snippets/whatsapp/send-button-quick-reply/curl

**Comment by pardel** [comment]
Closed due to inactivity.
